name: Test CPU info fetcher

on:
  push:
    branches:
      - '*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install Firefox
        run: |
          sudo apt remove -y firefox
          sudo add-apt-repository ppa:mozillateam/ppa
          sudo apt update && sudo apt install -y firefox-esr

      - name: Install Gecko
        run: |
          sudo mkdir /opt/geckodriver
          curl -s -L "https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz" | tar -xzvf - -C /opt/geckodriver
          echo 'export PATH="/opt/geckodriver:$PATH"' >> ~/.bashrc

      - name: Test with Gradle
        run: |
          ./gradlew test -i
      
      - name: Summarize tests results
        uses: jeantessier/test-summary-action@v1
        if: ${{ always() }}