name: Test CPU info fetcher

on:
  push:
    branches:
      - '*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
      
      - name: Setup Gecko Driver
        uses: browser-actions/setup-geckodriver@latest

      - name: Test with Gradle
        run: |
          ./gradlew test -i
      
      - name: Summarize tests results
        uses: jeantessier/test-summary-action@v1
        if: ${{ always() }}